version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.13.0-rc.4-management-alpine
    container_name: 'rabbitmq'
    environment:      
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/rabbitmq/rabbitmq_data:/var/lib/rabbitmq/
        - ./data/rabbitmq/rabbitmq_log:/var/log/rabbitmq
    networks:
        - internal-net

  db:
    depends_on: 
      - rabbitmq
    image: postgres:16.1    
    networks:
      - internal-net
    volumes:
      - ./data/postgres/db_data:/var/lib/postgresql/data
    environment:  
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres      
      - POSTGRES_PASSWORD=admin      
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
     
networks:
  internal-net:
    driver: bridge
